### ISSUE TITLE
Display currentFlow AND / OR currentLevel on same graph

### ISSUE THREAD

**Issue by fergusfrl** [fergusfrl/RiverWiki#20]
Currently, only currentFlow can be displayed on the graph / in current flow on list.
The problem is that gauges are present even if they only contain currentLevel so users can select the gauge but cannot see currentLevel.

Fix:
- option 1: display BOTH level and flow
- option 2: display one OR the other with flow taking priority over level (level will only be displayed if it is the only data point)

**Comment by pcrossnz** [comment]
Agreed, it will be useful to have if possible. I think either option is fine, dependant on the workload required!

**Comment by fergusfrl** [comment]
Have fixed using option 2 as was a quick easy fix.
I will open a new issue to include BOTH in the future
